I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter3.rpy", line 41, in script call
    call sitDown
  File "game/chapter3.rpy", line 41, in script call
    call sitDown
  File "game/chapter3.rpy", line 41, in script call
    call sitDown
  File "game/chapter3.rpy", line 51, in script
    scene bg blood wit Dissolve(5.0)
Exception: Image 'bg blood' does not accept attributes 'wit Dissolve (5.0)'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter3.rpy", line 41, in script call
    call sitDown
  File "game/chapter3.rpy", line 41, in script call
    call sitDown
  File "game/chapter3.rpy", line 41, in script call
    call sitDown
  File "game/chapter3.rpy", line 51, in script
    scene bg blood wit Dissolve(5.0)
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\ast.py", line 1245, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'bg blood' does not accept attributes 'wit Dissolve (5.0)'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.3.24111502
Исповедь Анархиста 1.0
Thu Dec 19 00:08:13 2024
