I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter3.rpy", line 50, in script call
    call sitDown
  File "game/chapter3.rpy", line 50, in script call
    call sitDown
  File "game/chapter3.rpy", line 50, in script call
    call sitDown
  File "game/chapter3.rpy", line 66, in script
    show screamer at up with vpunch
  File "game/chapter3.rpy", line 66, in <module>
    show screamer at up with vpunch
NameError: name 'up' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter3.rpy", line 50, in script call
    call sitDown
  File "game/chapter3.rpy", line 50, in script call
    call sitDown
  File "game/chapter3.rpy", line 50, in script call
    call sitDown
  File "game/chapter3.rpy", line 66, in script
    show screamer at up with vpunch
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\ast.py", line 1070, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\ast.py", line 1070, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Prog\Renpy\renpy-8.3.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/chapter3.rpy", line 66, in <module>
    show screamer at up with vpunch
NameError: name 'up' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.3.24111502
Исповедь Анархиста 1.0
Mon Dec 23 01:03:35 2024
